services:

    db:
        image: postgres:16-alpine
        container_name: postgres_db
        env_file: .env
        volumes:
            - pg_data:/db/data
            - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
        ports:
          - 6432:5432
        restart: always
        healthcheck:
            test: [ "CMD-SHELL", "pg_isready -U postgres" ]
            interval: 10s
            timeout: 5s
            retries: 5
    web:
        build: .
        container_name: web_app
        command: sh -c "sleep 5 && uvicorn main:app --host 0.0.0.0 --port 8000 --reload"
        volumes:
          - ./:/home/dev/app
        ports:
          - 12005:8000
        depends_on:
            db:
                condition: service_healthy
        restart: always
        env_file: .env

volumes:
    pg_data: